#!/bin/bash

sudo rabbitmqctl stop_app
sudo rabbitmqctl reset
sudo rabbitmqctl start_app

echo "########### queues ###########"
sudo rabbitmqctl list_queues
echo "########### consumers ###########"
sudo rabbitmqctl list_consumers
echo "########### connections ###########"
sudo rabbitmqctl list_connections
