#!/bin/bash

set -e
source findwars

destination="scastro@scastrors:/opt/abiquo/tomcat/webapps"

validWARs "CPP NC VSM VF BPM AM SSM M"

rss="$(evaluateInput $@)"

scp "$(findwars $rss)" $destination
