#!/bin/bash

set -e
source findwars

destination=$(remotedestination)

validWARs "API CPP NC VSM VF BPM AM SSM M"

rss="$(evaluateInput $@)"

echo "Copying to $destination"
scp $(findwars $rss) $destination
