#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script modifies the /etc/resolv.conf so requires to be run as root"
    exit 1
fi

sed -ie 's/nameserver 127.0.0.53//g' /etc/resolv.conf
grep 10.60.1.4 /etc/resolv.conf 2>&1 > /dev/null || echo nameserver 10.60.1.4 >> /etc/resolv.conf
