#!/bin/bash

set -e

WORKSPACE="$HOME/workspace/platform/"

CPP="cpp.war"
NC="nodecollector.war"
VSM="vsm.war"
VF="virtualfactory.war"
BPM="bpm-async.war"
AM="am.war"
SSM="ssm.war"
API="api.war"
M="m.war"

function findwars(){
    for WAR in $@;
    do
        ORIGIN="$ORIGIN $(find $WORKSPACE -name $WAR)"
    done
    echo $ORIGIN
}

function validWARs(){
    export VALID_WARS="$@"
}

function evaluateInput(){
    INWARS="$@"
    
    if [ -z "$1" ]
    then
        INWARS="$VALID_WARS"
    fi

    for WAR in $INWARS;
    do
        if  [[ " $VALID_WARS " == *\ $WAR\ * ]]
        then
            WARS="$WARS $(eval echo "\${$WAR}")"
        else
            # error message
            (>&2 echo "skiping $WAR because it's not a valid WAR")
        fi
    done

    if [ -z "$WARS" ]
    then
        (>&2 echo "$0 [$VALID_WARS]")
        exit 1
    fi

    echo $WARS
}
