#!/bin/bash
set -e

if [[ "$@" -eq "0" ]];
then
    echo "usage: scpjar <project> [<version>]"
    exit 1
fi

project=$1
version=$2

scp -r /home/sergi/.m2/repository/com/abiquo/$project/$version sergi@10.60.4.10:~/.m2/repository/com/abiquo/$project 
